const KEY='vc-routing-package';
const META='vc-routing-meta';
const R=6371000;
const rad=x=>x*Math.PI/180;
export function distance(a,b){const p=rad,dLat=rad(b.lat-a.lat),dLon=rad(b.lon-a.lon);const q=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
export function validatePackage(p){if(!p||p.schema!==1||!Array.isArray(p.nodes)||!Array.isArray(p.edges))throw new Error('Neispravan offline routing paket');if(!p.nodes.length||!p.edges.length)throw new Error('Routing paket nema cestovnu mrežu');return true}
export function installPackage(pkg){validatePackage(pkg);localStorage.setItem(KEY,JSON.stringify(pkg));localStorage.setItem(META,JSON.stringify({name:pkg.name||'Offline routing',version:pkg.version||'1',nodes:pkg.nodes.length,edges:pkg.edges.length,installedAt:new Date().toISOString()}));return packageInfo()}
export function removePackage(){localStorage.removeItem(KEY);localStorage.removeItem(META)}
export function packageInfo(){try{return JSON.parse(localStorage.getItem(META)||'null')}catch{return null}}
function load(){try{const p=JSON.parse(localStorage.getItem(KEY)||'null');if(!p)return null;validatePackage(p);return p}catch{return null}}
function nearest(nodes,p){let best=null,d=Infinity;for(const n of nodes){const x=distance(p,n);if(x<d){d=x;best=n}}return best}
export function route(start,end){const g=load();if(!g)throw new Error('Offline routing paket nije instaliran');const nodes=new Map(g.nodes.map(n=>[String(n.id),n]));const adj=new Map();for(const e of g.edges){const a=String(e.from),b=String(e.to);if(!nodes.has(a)||!nodes.has(b))continue;const w=Number(e.distance)||distance(nodes.get(a),nodes.get(b));if(!adj.has(a))adj.set(a,[]);if(!adj.has(b))adj.set(b,[]);adj.get(a).push({to:b,w});if(e.oneway!==true)adj.get(b).push({to:a,w})}const s=nearest(g.nodes,start),t=nearest(g.nodes,end);if(!s||!t)throw new Error('Nema odgovarajućih cestovnih čvorova');const dist=new Map([[String(s.id),0]]),prev=new Map(),open=new Set([String(s.id)]);while(open.size){let u=null,best=Infinity;for(const id of open){const d=dist.get(id)??Infinity;if(d<best){best=d;u=id}}open.delete(u);if(u===String(t.id))break;for(const e of adj.get(u)||[]){const nd=best+e.w;if(nd<(dist.get(e.to)??Infinity)){dist.set(e.to,nd);prev.set(e.to,u);open.add(e.to)}}}const tid=String(t.id);if(!dist.has(tid))throw new Error('Ruta nije pronađena');const ids=[];let cur=tid;while(cur!==undefined){ids.push(cur);if(cur===String(s.id))break;cur=prev.get(cur)}ids.reverse();return {distance:dist.get(tid),points:ids.map(id=>nodes.get(id)),from:s,to:t}}
export function exportPackage(){const p=load();return p?JSON.stringify(p):null}
