const KEY='vc-routing-package';
const META='vc-routing-meta';
const R=6371000;
const rad=x=>x*Math.PI/180;
const validCoord=(lat,lon)=>Number.isFinite(lat)&&Number.isFinite(lon)&&lat>=-90&&lat<=90&&lon>=-180&&lon<=180;
export function distance(a,b){if(!a||!b||!validCoord(Number(a.lat),Number(a.lon))||!validCoord(Number(b.lat),Number(b.lon)))throw new Error('Neispravne GPS koordinate');const dLat=rad(b.lat-a.lat),dLon=rad(b.lon-a.lon);const q=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
export function validatePackage(p){
  if(!p||p.schema!==1||!Array.isArray(p.nodes)||!Array.isArray(p.edges))throw new Error('Neispravan offline routing paket');
  if(!p.nodes.length||!p.edges.length)throw new Error('Routing paket nema cestovnu mrežu');
  const ids=new Set();
  for(const n of p.nodes){if(n===null||n===undefined||n.id===undefined||n.id===null||ids.has(String(n.id))||!validCoord(Number(n.lat),Number(n.lon)))throw new Error('Routing paket ima neispravan ili dupliciran čvor');ids.add(String(n.id))}
  for(const e of p.edges){if(!e||e.from===undefined||e.to===undefined||!ids.has(String(e.from))||!ids.has(String(e.to)))throw new Error('Routing paket ima neispravan spoj ceste');const w=e.distance===undefined?0:Number(e.distance);if(e.distance!==undefined&&(!Number.isFinite(w)||w<=0))throw new Error('Routing paket ima neispravnu udaljenost');if(e.oneway!==undefined&&typeof e.oneway!=='boolean')throw new Error('Routing paket ima neispravan smjer ceste')}
  if(p.places!==undefined){if(!Array.isArray(p.places))throw new Error('Routing paket ima neispravan popis mjesta');for(const x of p.places){if(!x||!String(x.name||'').trim()||!validCoord(Number(x.lat),Number(x.lon)))throw new Error('Routing paket ima neispravno mjesto')}}
  return true;
}
export function installPackage(pkg){validatePackage(pkg);localStorage.setItem(KEY,JSON.stringify(pkg));localStorage.setItem(META,JSON.stringify({name:pkg.name||'Offline routing',version:pkg.version||'1',nodes:pkg.nodes.length,edges:pkg.edges.length,places:Array.isArray(pkg.places)?pkg.places.length:0,installedAt:new Date().toISOString()}));return packageInfo()}
export function removePackage(){localStorage.removeItem(KEY);localStorage.removeItem(META)}
export function packageInfo(){try{return JSON.parse(localStorage.getItem(META)||'null')}catch{return null}}
function load(){try{const p=JSON.parse(localStorage.getItem(KEY)||'null');if(!p)return null;validatePackage(p);return p}catch{return null}}
function nearest(nodes,p){let best=null,d=Infinity;for(const n of nodes){const x=distance(p,n);if(x<d){d=x;best=n}}return best}
export function resolveDestination(query){const g=load();if(!g)throw new Error('Offline routing paket nije instaliran');const q=String(query||'').trim();const m=q.match(/^(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)$/);if(m){const lat=Number(m[1]),lon=Number(m[2]);if(!validCoord(lat,lon))throw new Error('Neispravne GPS koordinate odredišta');return {lat,lon}}const places=Array.isArray(g.places)?g.places:[];const exact=places.find(p=>String(p.name||'').toLowerCase()===q.toLowerCase());if(exact)return {lat:Number(exact.lat),lon:Number(exact.lon),name:exact.name};const part=places.find(p=>String(p.name||'').toLowerCase().includes(q.toLowerCase()));if(part)return {lat:Number(part.lat),lon:Number(part.lon),name:part.name};throw new Error('Odredište nije pronađeno u offline paketu')}
export function route(start,end){if(!start||!end||!validCoord(Number(start.lat),Number(start.lon))||!validCoord(Number(end.lat),Number(end.lon)))throw new Error('Neispravna početna ili završna GPS točka');const g=load();if(!g)throw new Error('Offline routing paket nije instaliran');const nodes=new Map(g.nodes.map(n=>[String(n.id),n]));const adj=new Map();for(const e of g.edges){const a=String(e.from),b=String(e.to);if(!nodes.has(a)||!nodes.has(b))continue;const supplied=Number(e.distance);const w=Number.isFinite(supplied)&&supplied>0?supplied:distance(nodes.get(a),nodes.get(b));if(!Number.isFinite(w)||w<=0)continue;if(!adj.has(a))adj.set(a,[]);if(!adj.has(b))adj.set(b,[]);adj.get(a).push({to:b,w});if(e.oneway!==true)adj.get(b).push({to:a,w})}const s=nearest(g.nodes,start),t=nearest(g.nodes,end);if(!s||!t)throw new Error('Nema odgovarajućih cestovnih čvorova');const dist=new Map([[String(s.id),0]]),prev=new Map(),open=new Set([String(s.id)]);while(open.size){let u=null,best=Infinity;for(const id of open){const d=dist.get(id)??Infinity;if(d<best){best=d;u=id}}if(u===null)break;open.delete(u);if(u===String(t.id))break;for(const e of adj.get(u)||[]){const nd=best+e.w;if(nd<(dist.get(e.to)??Infinity)){dist.set(e.to,nd);prev.set(e.to,u);open.add(e.to)}}}const tid=String(t.id);if(!dist.has(tid))throw new Error('Ruta nije pronađena');const ids=[];let cur=tid;while(cur!==undefined){ids.push(cur);if(cur===String(s.id))break;cur=prev.get(cur);if(ids.length>g.nodes.length+1)throw new Error('Neispravan routing graf')}if(ids[ids.length-1]!==String(s.id))throw new Error('Ruta nije pronađena');ids.reverse();return {distance:dist.get(tid),points:ids.map(id=>nodes.get(id)),from:s,to:t}}
