export const LANGUAGES = {
  hr:{name:'Hrvatski',flag:'🇭🇷',strings:{app:'VAŠ CHARLIE OS',subtitle:'Taxi • posao • navigacija • financije',start:'Pokreni vožnju',stop:'Završi vožnju',pause:'Pauza',resume:'Nastavi',navigation:'Navigacija',offline:'Offline način',online:'Online',destination:'Odredište',route:'Ruta',distance:'Udaljenost',time:'Vrijeme',settings:'Postavke',language:'Jezik'}},
  en:{name:'English',flag:'🇬🇧',strings:{app:'VAŠ CHARLIE OS',subtitle:'Taxi • work • navigation • finances',start:'Start ride',stop:'Finish ride',pause:'Pause',resume:'Resume',navigation:'Navigation',offline:'Offline mode',online:'Online',destination:'Destination',route:'Route',distance:'Distance',time:'Time',settings:'Settings',language:'Language'}},
  de:{name:'Deutsch',flag:'🇩🇪',strings:{app:'VAŠ CHARLIE OS',subtitle:'Taxi • Arbeit • Navigation • Finanzen',start:'Fahrt starten',stop:'Fahrt beenden',pause:'Pause',resume:'Fortsetzen',navigation:'Navigation',offline:'Offline-Modus',online:'Online',destination:'Ziel',route:'Route',distance:'Entfernung',time:'Zeit',settings:'Einstellungen',language:'Sprache'}},
  it:{name:'Italiano',flag:'🇮🇹',strings:{app:'VAŠ CHARLIE OS',subtitle:'Taxi • lavoro • navigazione • finanze',start:'Avvia corsa',stop:'Termina corsa',pause:'Pausa',resume:'Riprendi',navigation:'Navigazione',offline:'Modalità offline',online:'Online',destination:'Destinazione',route:'Percorso',distance:'Distanza',time:'Tempo',settings:'Impostazioni',language:'Lingua'}},
  sl:{name:'Slovenščina',flag:'🇸🇮',strings:{app:'VAŠ CHARLIE OS',subtitle:'Taxi • delo • navigacija • finance',start:'Začni vožnjo',stop:'Končaj vožnjo',pause:'Premor',resume:'Nadaljuj',navigation:'Navigacija',offline:'Način brez povezave',online:'Povezano',destination:'Cilj',route:'Pot',distance:'Razdalja',time:'Čas',settings:'Nastavitve',language:'Jezik'}},
  sk:{name:'Slovenčina',flag:'🇸🇰',strings:{app:'VAŠ CHARLIE OS',subtitle:'Taxi • práca • navigácia • financie',start:'Spustiť jazdu',stop:'Ukončiť jazdu',pause:'Pauza',resume:'Pokračovať',navigation:'Navigácia',offline:'Režim offline',online:'Online',destination:'Cieľ',route:'Trasa',distance:'Vzdialenosť',time:'Čas',settings:'Nastavenia',language:'Jazyk'}},
  cs:{name:'Čeština',flag:'🇨🇿',strings:{app:'VAŠ CHARLIE OS',subtitle:'Taxi • práce • navigace • finance',start:'Spustit jízdu',stop:'Ukončit jízdu',pause:'Pauza',resume:'Pokračovat',navigation:'Navigace',offline:'Offline režim',online:'Online',destination:'Cíl',route:'Trasa',distance:'Vzdálenost',time:'Čas',settings:'Nastavení',language:'Jazyk'}},
  pl:{name:'Polski',flag:'🇵🇱',strings:{app:'VAŠ CHARLIE OS',subtitle:'Taxi • praca • nawigacja • finanse',start:'Rozpocznij przejazd',stop:'Zakończ przejazd',pause:'Pauza',resume:'Wznów',navigation:'Nawigacja',offline:'Tryb offline',online:'Online',destination:'Cel',route:'Trasa',distance:'Odległość',time:'Czas',settings:'Ustawienia',language:'Język'}},
  fr:{name:'Français',flag:'🇫🇷',strings:{app:'VAŠ CHARLIE OS',subtitle:'Taxi • travail • navigation • finances',start:'Démarrer la course',stop:'Terminer la course',pause:'Pause',resume:'Reprendre',navigation:'Navigation',offline:'Mode hors ligne',online:'En ligne',destination:'Destination',route:'Itinéraire',distance:'Distance',time:'Temps',settings:'Paramètres',language:'Langue'}},
  es:{name:'Español',flag:'🇪🇸',strings:{app:'VAŠ CHARLIE OS',subtitle:'Taxi • trabajo • navegación • finanzas',start:'Iniciar viaje',stop:'Finalizar viaje',pause:'Pausa',resume:'Continuar',navigation:'Navegación',offline:'Modo sin conexión',online:'En línea',destination:'Destino',route:'Ruta',distance:'Distancia',time:'Tiempo',settings:'Ajustes',language:'Idioma'}},
  pt:{name:'Português',flag:'🇵🇹',strings:{app:'VAŠ CHARLIE OS',subtitle:'Táxi • trabalho • navegação • finanças',start:'Iniciar viagem',stop:'Terminar viagem',pause:'Pausa',resume:'Continuar',navigation:'Navegação',offline:'Modo offline',online:'Online',destination:'Destino',route:'Rota',distance:'Distância',time:'Tempo',settings:'Definições',language:'Idioma'}},
  hu:{name:'Magyar',flag:'🇭🇺',strings:{app:'VAŠ CHARLIE OS',subtitle:'Taxi • munka • navigáció • pénzügyek',start:'Fuvar indítása',stop:'Fuvar befejezése',pause:'Szünet',resume:'Folytatás',navigation:'Navigáció',offline:'Offline mód',online:'Online',destination:'Úticél',route:'Útvonal',distance:'Távolság',time:'Idő',settings:'Beállítások',language:'Nyelv'}}
};
export function getLanguage(){const saved=localStorage.getItem('vc-language');if(saved&&LANGUAGES[saved])return saved;const detected=(navigator.language||'hr').slice(0,2);return LANGUAGES[detected]?detected:'hr'}
